/* eslint-disable max-classes-per-file */
class ThemeToggle extends HTMLElement {

	connectedCallback() {
		const storedTheme = localStorage.getItem("deno-coverage-theme");
		const systemPrefersDark = globalThis.matchMedia("(prefers-color-scheme: dark)").matches;
		const initialTheme = storedTheme || (systemPrefersDark ? "dark" : "light");

		this.innerHTML = `
			<button id="theme-toggle" type="button" aria-label="Toggle dark mode">
				<svg class="dark-icon" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
					<path stroke="none" d="M0 0h24v24H0z" fill="none" />
					<path d="M12 1.992a10 10 0 1 0 9.236 13.838c.341 -.82 -.476 -1.644 -1.298 -1.31a6.5 6.5 0 0 1 -6.864 -10.787l.077 -.08c.551 -.63 .113 -1.653 -.758 -1.653h-.266l-.068 -.006l-.06 -.002z" />
				</svg>
				<svg class="light-icon" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
					<path stroke="none" d="M0 0h24v24H0z" fill="none" />
					<path d="M12 19a1 1 0 0 1 .993 .883l.007 .117v1a1 1 0 0 1 -1.993 .117l-.007 -.117v-1a1 1 0 0 1 1 -1z" />
					<path d="M18.313 16.91l.094 .083l.7 .7a1 1 0 0 1 -1.32 1.497l-.094 -.083l-.7 -.7a1 1 0 0 1 1.218 -1.567l.102 .07z" />
					<path d="M7.007 16.993a1 1 0 0 1 .083 1.32l-.083 .094l-.7 .7a1 1 0 0 1 -1.497 -1.32l.083 -.094l.7 -.7a1 1 0 0 1 1.414 0z" />
					<path d="M4 11a1 1 0 0 1 .117 1.993l-.117 .007h-1a1 1 0 0 1 -.117 -1.993l.117 -.007h1z" />
					<path d="M21 11a1 1 0 0 1 .117 1.993l-.117 .007h-1a1 1 0 0 1 -.117 -1.993l.117 -.007h1z" />
					<path d="M6.213 4.81l.094 .083l.7 .7a1 1 0 0 1 -1.32 1.497l-.094 -.083l-.7 -.7a1 1 0 0 1 1.217 -1.567l.102 .07z" />
					<path d="M19.107 4.893a1 1 0 0 1 .083 1.32l-.083 .094l-.7 .7a1 1 0 0 1 -1.497 -1.32l.083 -.094l.7 -.7a1 1 0 0 1 1.414 0z" />
					<path d="M12 2a1 1 0 0 1 .993 .883l.007 .117v1a1 1 0 0 1 -1.993 .117l-.007 -.117v-1a1 1 0 0 1 1 -1z" />
					<path d="M12 7a5 5 0 1 1 -4.995 5.217l-.005 -.217l.005 -.217a5 5 0 0 1 4.995 -4.783z" />
				</svg>
			</button>
		`;

		this.updateIcons(initialTheme);

		this.querySelector("button").addEventListener("click", () => {
			const isDark = document.documentElement.classList.contains("dark");
			const newTheme = isDark ? "light" : "dark";

			this.setTheme(newTheme);
		});
	}

	setTheme(theme) {
		document.documentElement.classList.remove("dark", "light");
		document.documentElement.classList.add(theme);
		localStorage.setItem("deno-coverage-theme", theme);
		this.updateIcons(theme);
	}

	updateIcons(theme) {
		const darkIcon = this.querySelector(".dark-icon");
		const lightIcon = this.querySelector(".light-icon");

		darkIcon.style.display = theme === "dark" ? "none" : "block";
		lightIcon.style.display = theme === "dark" ? "block" : "none";
	}

}

class CoverageBar extends HTMLElement {

	connectedCallback() {
		const value = this.getAttribute("value") || "0";

		this.innerHTML = `<div class="chart"><div class="cover-fill" style="width: ${value}%"></div><div class="cover-empty" style="width: calc(100% - ${value}%)"></div></div>`;
	}

}

class CoveragePage extends HTMLElement {

	connectedCallback() {
		setTimeout(() => this.render(), 0);
	}

	render() {
		const title = this.getAttribute("title") || "";
		const branchesPct = this.getAttribute("branches-pct") || "0%";
		const branchesFraction = this.getAttribute("branches-fraction") || "0/0";
		const linesPct = this.getAttribute("lines-pct") || "0%";
		const linesFraction = this.getAttribute("lines-fraction") || "0/0";
		const status = this.getAttribute("status") || "high";

		const content = this.innerHTML;

		this.innerHTML = `
			<div class="wrapper">
				<div class="pad1 flex-header">
					<div>
						<h1>${title}</h1>
						<div class="clearfix">
							<div class="fl pad1y space-right2">
								<span class="strong">${branchesPct}</span>
								<span class="quiet">Branches</span>
								<span class="fraction">${branchesFraction}</span>
							</div>
							<div class="fl pad1y space-right2">
								<span class="strong">${linesPct}</span>
								<span class="quiet">Lines</span>
								<span class="fraction">${linesFraction}</span>
							</div>
						</div>
					</div>
					<theme-toggle></theme-toggle>
				</div>
				<div class="status-line ${status}"></div>
				<div class="pad1 overflow-auto">${content}</div>
				<div class="push"></div>
			</div>
			<div class="footer quiet pad2 space-top1 center small">
				Code coverage generated by
				<a href="https://deno.com/" target="_blank">Deno</a>
			</div>
		`;
	}

}

customElements.define("theme-toggle", ThemeToggle);
customElements.define("coverage-bar", CoverageBar);
customElements.define("coverage-page", CoveragePage);

const theme = localStorage.getItem("deno-coverage-theme") ||
	(globalThis.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");

document.documentElement.classList.add(theme);
